### ISSUE TITLE
Not working on small int boards

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_MS8607#3]
Trinket M0 for example:
```python
Adafruit CircuitPython 5.3.1 on 2020-07-13; Adafruit Trinket M0 with samd21e18
>>> import board
>>> from adafruit_ms8607 import MS8607
>>> sensor = MS8607(board.I2C())
>>> sensor.pressure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ms8607.py", line 313, in pressure
  File "adafruit_ms8607.py", line 190, in pressure_and_temperature
  File "adafruit_ms8607.py", line 199, in _scale_temp_pressure
OverflowError: small int overflow
>>> 
```

**Comment by siddacious** [comment]
This was mentioned in a forum thread an be I said I'd take a look at modifying the conversion math to allow it to be done with small ints.

The original post seemed to show humidity working if called first, but a following call to`temperature` failing with the above error

**Comment by siddacious** [comment]
The MS8607 has separate sensors in one package for humidity and temp+pressure. It looks like the humidity sensor works without issue but the calibration-related code for the T+P sensor is having issues. I took a look over the weekend and it does look like there is room to use smaller numbers


![image](https://user-images.githubusercontent.com/1183985/95118939-fe6e4a00-06ff-11eb-8636-4f90e90be127.png)

**Comment by HydroflameUTCS** [comment]
this is still an issue, the m0 is still unable to process temperature and pressure with a small int overflow, will a solution to the math be released at some point?
